version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - kay_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - kay_static:/data/static/
      - kay_media:/data/media/

  django:
    image: kay_django:3
    networks:
      - kay_network
    volumes:
      - kay_static:/home/kay/staticfiles/
      - kay_media:/home/kay/media/



networks:
  kay_network:

volumes:
  kay_static:
  kay_media:







