version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - kay_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - kay_static:/data/static/
      - kay_media:/data/media/

  django:
    image: kay_django:4
    networks:
      - kay_network
    volumes:
      - kay_static:/home/kay/staticfiles/
      - kay_media:/home/kay/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD


  mariadb:
    image: mariadb:10.5
    networks:
      - kay_network
    volumes:
      - kay_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
     MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  kay_network:

volumes:
  kay_static:
  kay_media:
  kay_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true



